src/main/java/org/gcube/portlets/user/performfish/bean/CompanyMember.java
package org.gcube.portlets.user.performfish.bean;

import java.util.ArrayList;
import java.util.List;

import org.gcube.vomanagement.usermanagement.model.GCubeUser;

public class CompanyMember {
	private GCubeUser user;
	private List<Farm> associatedFarms = new ArrayList<>();
	private boolean isAdmin;
	public CompanyMember(GCubeUser user) {
		super();
		this.user = user;
	}
	
	public boolean isAdmin() {
		return isAdmin;
	}

	public void setAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	public GCubeUser getUser() {
		return user;
	}
	public void setUser(GCubeUser user) {
		this.user = user;
	}
	
	
	
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("CompanyMember [user=");
		builder.append(user);
		builder.append(", associatedFarms=");
		builder.append(associatedFarms);
		builder.append(", isAdmin=");
		builder.append(isAdmin);
		builder.append("]");
		return builder.toString();
	}

	public List<Farm> getAssociatedFarms() {
		return associatedFarms;
	}
	
	public String getAssociatedFarmNames() {
		String toReturn = "";
		for (Farm farm : associatedFarms) {
			toReturn += " " + farm.getName();
		}
		return toReturn;
	}

	public void setAssociatedFarms(List<Farm> associatedFarms) {
		this.associatedFarms = associatedFarms;
	}

	public String getUserAvatarURL() {
		return this.user.getUserAvatarURL();
	}
	
	public String getjobTitle() {
		return this.user.getJobTitle();
	}
	
	public String getFullname() {
		return this.user.getFullname();
	}
	public long getUserId() {
		return this.user.getUserId();
	}
	
	public String getUsername() {
		return this.user.getUsername();
	}
	
	public String getEmail() {
		return this.user.getEmail();
	}
	
	public void setEmail(String email) {
		this.user.setEmail(email);
	}

}

src/main/webapp/html/editcompanyusers/edit_admin_users.jsp
<%@page import="org.apache.tika.sax.ToTextContentHandler"%>
<%@include file="../init.jsp"%>

<p class="lead">Administrators currently associated to <%= team.getName() %>:</p>


<liferay-portlet:renderURL varImpl="iteratorURL">
</liferay-portlet:renderURL>

<%
	String orderByCol = ParamUtil.getString(request, "orderByCol");
	String orderByType = ParamUtil.getString(request, "orderByType");
	String sortingOrder = orderByType;

	//Logic for toggle asc and desc
	if (orderByType.equals("desc"))
		orderByType = "asc";
	else
		orderByType = "desc";
	if (Validator.isNull(orderByType)) {
		orderByType = "asc";
	}
%>

<aui:form action="<%=portletURLString%>" method="post" name="fm">

	<liferay-ui:search-container var="searchContainer" delta="5"
		deltaConfigurable="true"
		emptyResultsMessage="Sorry. There are no users to display."
		iteratorURL="<%=iteratorURL%>" rowChecker="<%=rowChecker%>"
		orderByType="<%=orderByType%>">

		<liferay-ui:search-container-results>
			<%
				int totalUsers = admins.size();
				List<CompanyMember> sortableUsers = ListUtil.subList(admins, searchContainer.getStart(),
									searchContainer.getEnd());

				if (Validator.isNotNull(orderByCol)) {
					Collections.sort(sortableUsers, new CompanyMemberComparator());
					if (sortingOrder.equalsIgnoreCase("desc"))
						Collections.reverse(sortableUsers);
				}
				pageContext.setAttribute("results", sortableUsers);
				pageContext.setAttribute("total", totalUsers);
			%>
		</liferay-ui:search-container-results>

		<liferay-ui:search-container-row
				className="org.gcube.portlets.user.performfish.bean.CompanyMember"
			modelVar="item" keyProperty="userId">
			<liferay-ui:search-container-column-text orderable="true" name="Name">${item.fullname}</liferay-ui:search-container-column-text>
			<liferay-ui:search-container-column-text name="Email">${item.email}</liferay-ui:search-container-column-text>
			<liferay-ui:search-container-column-text name="Job Title">${item.jobTitle}</liferay-ui:search-container-column-text>
			<c:set var="FarmAdministrator"></c:set>
			<c:if test="${item.admin}">
				<c:set var="FarmAdministrator">(Farm Administrator)</c:set>
			</c:if>
			<liferay-ui:search-container-column-text name="Farms"> ${item.associatedFarmNames} ${FarmAdministrator} </liferay-ui:search-container-column-text>
			<portlet:actionURL name="removeFarmUsers" var="removeFarmUsersURL">
				<portlet:param name="currentUsername" value="<%= currentUsername %>" />
				<portlet:param name="currentGroupId" value="${currentGroupId}" />
				<portlet:param name="companyUserId" value="${item.userId}" />
				<portlet:param name="companyId" value="<%= Long.toString(team.getTeamId()) %>" />
			</portlet:actionURL>
			<%
			 final String hrefFix = "location.href='" + removeFarmUsersURL .toString()+"'";
			 %>
			<liferay-ui:search-container-column-button name="Remove from Farms"
				href="<%=hrefFix%>" />
		</liferay-ui:search-container-row>
		<liferay-ui:search-iterator />
	</liferay-ui:search-container>
	<button name="delete" type="button" icon="icon-delete"
		class="btn btn-warning"
		onClick='<%=renderResponse.getNamespace() + "removeAdministratorRoleFromUsers();"%>'>Remove Administrator role from selected</button>
	<aui:input name="removeUserIds" type="hidden" />
	<aui:input name="teamId" type="hidden" value="<%= team.getTeamId() %>"/>
	<aui:input name="currentUsername" type="hidden" value="<%= currentUsername %>"/>
	<aui:input name="currentGroupId" type="hidden" value="<%= currentGroupId %>"/>
	<input id="totalUsers" name="no" type="hidden" value="<%= admins.size() %>"/>
</aui:form>

<aui:script>
	Liferay.provide(
		window,
		'<portlet:namespace />removeAdministratorRoleFromUsers',
		function() {
			var removeUserIds = Liferay.Util.listCheckedExcept(document.<portlet:namespace />fm, '<portlet:namespace />allRowIds');	
			var array = removeUserIds.split(',');
			var totalUsers = document.getElementById('totalUsers');

			if (array.length == totalUsers.value) {
				alert("Forbidden: You are  trying removing the role from all the users of the company, at least one must have it.")
				return;
			}
			if (removeUserIds && confirm("Are you sure you want to remove the Administrator role from the selected users?")) {
				document.<portlet:namespace />fm.<portlet:namespace />removeUserIds.value = removeUserIds;

				submitForm(document.<portlet:namespace />fm, '<portlet:actionURL name="removeAdministratorRoleFromUsers"></portlet:actionURL>');
			} else {
				
			}
		},
		['liferay-util-list-fields']
	);
</aui:script>

src/main/webapp/html/editcompanyusers/edit_company_users.jsp
<%@include file="../init.jsp"%>

<p class="lead">
	Users currently associated to
	<%= team.getName() %>:
</p>


<liferay-portlet:renderURL varImpl="iteratorURL">
</liferay-portlet:renderURL>

<%
	String orderByCol = ParamUtil.getString(request, "orderByCol");
	String orderByType = ParamUtil.getString(request, "orderByType");
	String sortingOrder = orderByType;

	//Logic for toggle asc and desc
	if (orderByType.equals("desc"))
		orderByType = "asc";
	else
		orderByType = "desc";
	if (Validator.isNull(orderByType)) {
		orderByType = "asc";
	}
%>

<c:set var="currentGroupId"><%=currentGroupId %></c:set>

<aui:form action="<%=portletURLString%>" method="post" name="fm">

	<liferay-ui:search-container var="searchContainer" delta="5"
		deltaConfigurable="true"
		emptyResultsMessage="Sorry. There are no users to display."
		iteratorURL="<%=iteratorURL%>" rowChecker="<%=rowChecker%>"
		orderByType="<%=orderByType%>">

		<liferay-ui:search-container-results>
			<%
				int totalUsers = teamUsers.size();
				List<CompanyMember> sortableUsers = ListUtil.subList(teamUsers, searchContainer.getStart(),
									searchContainer.getEnd());

				if (Validator.isNotNull(orderByCol)) {
					Collections.sort(sortableUsers, new CompanyMemberComparator());
					if (sortingOrder.equalsIgnoreCase("desc"))
						Collections.reverse(sortableUsers);
				}
				pageContext.setAttribute("results", sortableUsers);
				pageContext.setAttribute("total", totalUsers);
			%>
		</liferay-ui:search-container-results>

		<liferay-ui:search-container-row
			className="org.gcube.portlets.user.performfish.bean.CompanyMember"
			modelVar="item" keyProperty="username">
			<liferay-ui:search-container-column-text orderable="true" name="Name">${item.fullname}</liferay-ui:search-container-column-text>
			<liferay-ui:search-container-column-text name="Email">${item.email}</liferay-ui:search-container-column-text>
			<c:set var="FarmAdministrator"></c:set>
			<c:if test="${item.admin}">
				<c:set var="FarmAdministrator">(Farm Administrator)</c:set>
			</c:if>
			<liferay-ui:search-container-column-text name="Farms"> ${item.associatedFarmNames} ${FarmAdministrator} </liferay-ui:search-container-column-text>
			<portlet:actionURL name="removeFarmUsers" var="removeFarmUsersURL">
				<portlet:param name="currentUsername" value="<%= currentUsername %>" />
				<portlet:param name="currentGroupId" value="${currentGroupId}" />
				<portlet:param name="companyUserId" value="${item.userId}" />
				<portlet:param name="companyId" value="<%= Long.toString(team.getTeamId()) %>" />
			</portlet:actionURL>
			<%
			 final String hrefFix = "location.href='" + removeFarmUsersURL .toString()+"'";
			 %>
			<liferay-ui:search-container-column-button name="Remove from Farms"
				href="<%=hrefFix%>" />
		</liferay-ui:search-container-row>
		<liferay-ui:search-iterator />
	</liferay-ui:search-container>
	<button name="delete" type="button" icon="icon-delete"
		class="btn btn-warning"
		onClick='<%=renderResponse.getNamespace() + "removeCompanUsers();"%>'>Remove
		from Company</button>
	<aui:input name="removeUserIds" type="hidden" />
	<aui:input name="teamId" type="hidden" value="<%= team.getTeamId() %>" />
	<aui:input name="currentUsername" type="hidden"
		value="<%= currentUsername %>" />
	<aui:input name="currentGroupId" type="hidden"
		value="<%= currentGroupId %>" />

</aui:form>

<aui:script>
	Liferay.provide(
		window,
		'<portlet:namespace />removeCompanUsers',
		function() {
			var removeUserIds = Liferay.Util.listCheckedExcept(document.<portlet:namespace />fm, '<portlet:namespace />allRowIds');	
			
			if (removeUserIds && confirm("Are you sure you want to remove the selected users from this company?")) {
				document.<portlet:namespace />fm.<portlet:namespace />removeUserIds.value = removeUserIds;

				submitForm(document.<portlet:namespace />fm, '<portlet:actionURL name="removeCompanUsers"></portlet:actionURL>');
			} else {
				
			}
		},
		['liferay-util-list-fields']
	);
</aui:script>