src/main/java/org/gcube/portlets/user/performfish/bean/CompanyMember.java
package org.gcube.portlets.user.performfish.bean;

import java.util.ArrayList;
import java.util.List;

import org.gcube.vomanagement.usermanagement.model.GCubeUser;

public class CompanyMember {
	private GCubeUser user;
	private List<Farm> associatedFarms = new ArrayList<>();
	private boolean isAdmin;
	public CompanyMember(GCubeUser user) {
		super();
		this.user = user;
	}
	
	public boolean isAdmin() {
		return isAdmin;
	}

	public void setAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	public GCubeUser getUser() {
		return user;
	}
	public void setUser(GCubeUser user) {
		this.user = user;
	}
	
	
	
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("CompanyMember [user=");
		builder.append(user);
		builder.append(", associatedFarms=");
		builder.append(associatedFarms);
		builder.append(", isAdmin=");
		builder.append(isAdmin);
		builder.append("]");
		return builder.toString();
	}

	public List<Farm> getAssociatedFarms() {
		return associatedFarms;
	}
	
	public String getAssociatedFarmNames() {
		String toReturn = "";
		for (Farm farm : associatedFarms) {
			toReturn += " " + farm.getName();
		}
		return toReturn;
	}

	public void setAssociatedFarms(List<Farm> associatedFarms) {
		this.associatedFarms = associatedFarms;
	}

	public String getUserAvatarURL() {
		return this.user.getUserAvatarURL();
	}
	
	public String getjobTitle() {
		return this.user.getJobTitle();
	}
	
	public String getFullname() {
		return this.user.getFullname();
	}
	public long getUserId() {
		return this.user.getUserId();
	}
	
	public String getUsername() {
		return this.user.getUsername();
	}
	
	public String getEmail() {
		return this.user.getEmail();
	}
	
	public void setEmail(String email) {
		this.user.setEmail(email);
	}

}

src/main/webapp/html/managefarmusers/manage_farm_users_view.jsp
<%@include file="../init.jsp"%>

<%
	List<GCubeUser> members = (List<GCubeUser>) renderRequest.getAttribute("farmMembers");
	pageContext.setAttribute("farmMembers", members);
	pageContext.setAttribute("logoURL", renderRequest.getAttribute("companyLogoURL"));
	String portletURLString = PortalUtil.getCurrentURL(request);
	RowChecker rowChecker = new RowChecker(renderResponse);
	String currentUsername = Utils.getCurrentUser(request).getUsername();
	Team farm = (Team) request.getAttribute("theFarm");
	pageContext.setAttribute("farmName", farm.getName());
	pageContext.setAttribute("theFarmId", farm.getTeamId());
	GCubeTeam theCompany = (GCubeTeam) request.getAttribute("theCompany");
	pageContext.setAttribute("theCompanyName", theCompany.getTeamName());
	
	long currentGroupId = PortalUtil.getScopeGroupId(request);
	String currentURL = PortalUtil.getCurrentURL(request);
	//this is the list to be working on manage
	List<GCubeUser> teamUsers = members;
%>

<portlet:renderURL var="maximizedState"
	windowState="<%=LiferayWindowState.MAXIMIZED.toString()%>" />
<portlet:renderURL var="normalState"
	windowState="<%=LiferayWindowState.NORMAL.toString()%>" />

<c:set var="maximised" scope="session"
	value="${renderRequest.getWindowState().toString().equalsIgnoreCase('maximized')}" />
<div style="text-align: center; padding-bottom: 15px;">
	<table>
		<tr>
			<c:if test="${not empty logoURL}">
				<td>
					<img class="logo-circular" src="${logoURL}" />
				</td>
			</c:if>
			<td><p style="font-size: 1.5em;padding-top: 12px; padding-left: 5px;">${theCompanyName} / ${farmName} - Users</p></td>
		</tr>
	</table>
</div>
<c:choose>
	<c:when test="${not maximised}">
		<div style="width: 100%; text-align: left; color: #3B5998;">
			<table id="example" class="display">
				<tbody>
					<c:forEach var="member" items="${farmMembers}">
						<%
							GCubeUser theUser = (GCubeUser) pageContext.getAttribute("member");
							String userProfileLink = Utils.getUserProfileLink(theUser.getUsername());
						%>
						<tr>
							<td><img src="${member.userAvatarURL}"
								style="width: 24px; padding-right: 10px;"></td>
							<td><span style="font-size: 1.3em;"><a
									href="<%= userProfileLink %>">${member.fullname}</a></span></td>
						</tr>
					</c:forEach>
				</tbody>
			</table>
			<div style="padding: 15px 0;">
				<a class="btn btn-primary" href="${maximizedState}&farmId=${theFarmId}"">Manage Farm regular users</a>
			</div>
		</div>
	</c:when>
	<c:otherwise>
		<a class="btn btn-link btn-large no-padding" href="${normalState}"><i
			class="icon icon-angle-left"></i>&nbsp;Back to Dashboard</a>
			<% 
			String encodedFarmId = Utils.maskId(farm.getTeamId());
			pageContext.setAttribute("encodedFarmId", encodedFarmId);%>
		<a class="btn btn-link btn-large" href="manage-farm-users?<%=Utils.ENCODED_FARM_PARAM %>=${encodedFarmId}"><i
			class="icon icon-angle-right"></i>&nbsp;Associate new users to the
			Farm</a>

		<%@include file="/html/editfarmusers/edit_farm_users.jsp"%>
	</c:otherwise>
</c:choose>